name: Dart

on: [push]
jobs:
  build:
    name: Check flutter lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
      - uses: subosito/flutter-action@v1.5.3
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Run linter
        run: dart analyze .
