name: (CLIENT) Dart lint

on: [push]
jobs:
  build:
    name: Check flutter lint
    runs-on: ubuntu-latest
    env:
      working-directory: client
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
      - uses: subosito/flutter-action@v1.5.3
        with:
          channel: "stable"
      - name: Install dependencies
        run: flutter pub get
        working-directory: ${{env.working-directory}}

      - name: Run linter
        run: dart analyze .
        working-directory: ${{env.working-directory}}
