name: (SERVER) Check ESLint

on: [push]
jobs:
  one:
    runs-on: ubuntu-latest
    env:
      working-directory: server
    steps:
      - uses: actions/checkout@v2
      - name: Init node env
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - run: cd server
      - name: npm install
        run: npm i --force
      - name: Check ESLint
        run: npm run fix:lint
        env:
          CI: true
